/*
HREG API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ParamDefines type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ParamDefines{}

// ParamDefines struct for ParamDefines
type ParamDefines struct {
	ParamId float32 `json:"param_id"`
	HregName NullableString `json:"hreg_name"`
	LabelDetail NullableString `json:"label_detail"`
	LabelChart NullableString `json:"label_chart"`
	ParamUsage NullableFloat32 `json:"param_usage"`
	UnitDetail NullableString `json:"unit_detail"`
	AttribDetail NullableString `json:"attrib_detail"`
	Access NullableString `json:"access"`
}

type _ParamDefines ParamDefines

// NewParamDefines instantiates a new ParamDefines object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParamDefines(paramId float32, hregName NullableString, labelDetail NullableString, labelChart NullableString, paramUsage NullableFloat32, unitDetail NullableString, attribDetail NullableString, access NullableString) *ParamDefines {
	this := ParamDefines{}
	this.ParamId = paramId
	this.HregName = hregName
	this.LabelDetail = labelDetail
	this.LabelChart = labelChart
	this.ParamUsage = paramUsage
	this.UnitDetail = unitDetail
	this.AttribDetail = attribDetail
	this.Access = access
	return &this
}

// NewParamDefinesWithDefaults instantiates a new ParamDefines object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParamDefinesWithDefaults() *ParamDefines {
	this := ParamDefines{}
	return &this
}

// GetParamId returns the ParamId field value
func (o *ParamDefines) GetParamId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ParamId
}

// GetParamIdOk returns a tuple with the ParamId field value
// and a boolean to check if the value has been set.
func (o *ParamDefines) GetParamIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ParamId, true
}

// SetParamId sets field value
func (o *ParamDefines) SetParamId(v float32) {
	o.ParamId = v
}

// GetHregName returns the HregName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ParamDefines) GetHregName() string {
	if o == nil || o.HregName.Get() == nil {
		var ret string
		return ret
	}

	return *o.HregName.Get()
}

// GetHregNameOk returns a tuple with the HregName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParamDefines) GetHregNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.HregName.Get(), o.HregName.IsSet()
}

// SetHregName sets field value
func (o *ParamDefines) SetHregName(v string) {
	o.HregName.Set(&v)
}

// GetLabelDetail returns the LabelDetail field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ParamDefines) GetLabelDetail() string {
	if o == nil || o.LabelDetail.Get() == nil {
		var ret string
		return ret
	}

	return *o.LabelDetail.Get()
}

// GetLabelDetailOk returns a tuple with the LabelDetail field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParamDefines) GetLabelDetailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LabelDetail.Get(), o.LabelDetail.IsSet()
}

// SetLabelDetail sets field value
func (o *ParamDefines) SetLabelDetail(v string) {
	o.LabelDetail.Set(&v)
}

// GetLabelChart returns the LabelChart field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ParamDefines) GetLabelChart() string {
	if o == nil || o.LabelChart.Get() == nil {
		var ret string
		return ret
	}

	return *o.LabelChart.Get()
}

// GetLabelChartOk returns a tuple with the LabelChart field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParamDefines) GetLabelChartOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LabelChart.Get(), o.LabelChart.IsSet()
}

// SetLabelChart sets field value
func (o *ParamDefines) SetLabelChart(v string) {
	o.LabelChart.Set(&v)
}

// GetParamUsage returns the ParamUsage field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *ParamDefines) GetParamUsage() float32 {
	if o == nil || o.ParamUsage.Get() == nil {
		var ret float32
		return ret
	}

	return *o.ParamUsage.Get()
}

// GetParamUsageOk returns a tuple with the ParamUsage field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParamDefines) GetParamUsageOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParamUsage.Get(), o.ParamUsage.IsSet()
}

// SetParamUsage sets field value
func (o *ParamDefines) SetParamUsage(v float32) {
	o.ParamUsage.Set(&v)
}

// GetUnitDetail returns the UnitDetail field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ParamDefines) GetUnitDetail() string {
	if o == nil || o.UnitDetail.Get() == nil {
		var ret string
		return ret
	}

	return *o.UnitDetail.Get()
}

// GetUnitDetailOk returns a tuple with the UnitDetail field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParamDefines) GetUnitDetailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UnitDetail.Get(), o.UnitDetail.IsSet()
}

// SetUnitDetail sets field value
func (o *ParamDefines) SetUnitDetail(v string) {
	o.UnitDetail.Set(&v)
}

// GetAttribDetail returns the AttribDetail field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ParamDefines) GetAttribDetail() string {
	if o == nil || o.AttribDetail.Get() == nil {
		var ret string
		return ret
	}

	return *o.AttribDetail.Get()
}

// GetAttribDetailOk returns a tuple with the AttribDetail field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParamDefines) GetAttribDetailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AttribDetail.Get(), o.AttribDetail.IsSet()
}

// SetAttribDetail sets field value
func (o *ParamDefines) SetAttribDetail(v string) {
	o.AttribDetail.Set(&v)
}

// GetAccess returns the Access field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ParamDefines) GetAccess() string {
	if o == nil || o.Access.Get() == nil {
		var ret string
		return ret
	}

	return *o.Access.Get()
}

// GetAccessOk returns a tuple with the Access field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParamDefines) GetAccessOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Access.Get(), o.Access.IsSet()
}

// SetAccess sets field value
func (o *ParamDefines) SetAccess(v string) {
	o.Access.Set(&v)
}

func (o ParamDefines) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ParamDefines) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["param_id"] = o.ParamId
	toSerialize["hreg_name"] = o.HregName.Get()
	toSerialize["label_detail"] = o.LabelDetail.Get()
	toSerialize["label_chart"] = o.LabelChart.Get()
	toSerialize["param_usage"] = o.ParamUsage.Get()
	toSerialize["unit_detail"] = o.UnitDetail.Get()
	toSerialize["attrib_detail"] = o.AttribDetail.Get()
	toSerialize["access"] = o.Access.Get()
	return toSerialize, nil
}

func (o *ParamDefines) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"param_id",
		"hreg_name",
		"label_detail",
		"label_chart",
		"param_usage",
		"unit_detail",
		"attrib_detail",
		"access",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varParamDefines := _ParamDefines{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varParamDefines)

	if err != nil {
		return err
	}

	*o = ParamDefines(varParamDefines)

	return err
}

type NullableParamDefines struct {
	value *ParamDefines
	isSet bool
}

func (v NullableParamDefines) Get() *ParamDefines {
	return v.value
}

func (v *NullableParamDefines) Set(val *ParamDefines) {
	v.value = val
	v.isSet = true
}

func (v NullableParamDefines) IsSet() bool {
	return v.isSet
}

func (v *NullableParamDefines) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParamDefines(val *ParamDefines) *NullableParamDefines {
	return &NullableParamDefines{value: val, isSet: true}
}

func (v NullableParamDefines) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParamDefines) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


