/*
HREG API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiUserGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiUserGet200Response{}

// ApiUserGet200Response struct for ApiUserGet200Response
type ApiUserGet200Response struct {
	Users []User `json:"users"`
}

type _ApiUserGet200Response ApiUserGet200Response

// NewApiUserGet200Response instantiates a new ApiUserGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiUserGet200Response(users []User) *ApiUserGet200Response {
	this := ApiUserGet200Response{}
	this.Users = users
	return &this
}

// NewApiUserGet200ResponseWithDefaults instantiates a new ApiUserGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiUserGet200ResponseWithDefaults() *ApiUserGet200Response {
	this := ApiUserGet200Response{}
	return &this
}

// GetUsers returns the Users field value
func (o *ApiUserGet200Response) GetUsers() []User {
	if o == nil {
		var ret []User
		return ret
	}

	return o.Users
}

// GetUsersOk returns a tuple with the Users field value
// and a boolean to check if the value has been set.
func (o *ApiUserGet200Response) GetUsersOk() ([]User, bool) {
	if o == nil {
		return nil, false
	}
	return o.Users, true
}

// SetUsers sets field value
func (o *ApiUserGet200Response) SetUsers(v []User) {
	o.Users = v
}

func (o ApiUserGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiUserGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["users"] = o.Users
	return toSerialize, nil
}

func (o *ApiUserGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"users",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiUserGet200Response := _ApiUserGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiUserGet200Response)

	if err != nil {
		return err
	}

	*o = ApiUserGet200Response(varApiUserGet200Response)

	return err
}

type NullableApiUserGet200Response struct {
	value *ApiUserGet200Response
	isSet bool
}

func (v NullableApiUserGet200Response) Get() *ApiUserGet200Response {
	return v.value
}

func (v *NullableApiUserGet200Response) Set(val *ApiUserGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiUserGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiUserGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiUserGet200Response(val *ApiUserGet200Response) *NullableApiUserGet200Response {
	return &NullableApiUserGet200Response{value: val, isSet: true}
}

func (v NullableApiUserGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiUserGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


