/*
HREG API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ParamUp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ParamUp{}

// ParamUp struct for ParamUp
type ParamUp struct {
	UpId float32 `json:"up_id"`
	ParamId NullableFloat32 `json:"param_id"`
	DeviceId NullableFloat32 `json:"device_id"`
	ValueStr NullableString `json:"value_str"`
	UpTime NullableTime `json:"up_time"`
	UpSss NullableFloat32 `json:"up_sss"`
}

type _ParamUp ParamUp

// NewParamUp instantiates a new ParamUp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParamUp(upId float32, paramId NullableFloat32, deviceId NullableFloat32, valueStr NullableString, upTime NullableTime, upSss NullableFloat32) *ParamUp {
	this := ParamUp{}
	this.UpId = upId
	this.ParamId = paramId
	this.DeviceId = deviceId
	this.ValueStr = valueStr
	this.UpTime = upTime
	this.UpSss = upSss
	return &this
}

// NewParamUpWithDefaults instantiates a new ParamUp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParamUpWithDefaults() *ParamUp {
	this := ParamUp{}
	return &this
}

// GetUpId returns the UpId field value
func (o *ParamUp) GetUpId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.UpId
}

// GetUpIdOk returns a tuple with the UpId field value
// and a boolean to check if the value has been set.
func (o *ParamUp) GetUpIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpId, true
}

// SetUpId sets field value
func (o *ParamUp) SetUpId(v float32) {
	o.UpId = v
}

// GetParamId returns the ParamId field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *ParamUp) GetParamId() float32 {
	if o == nil || o.ParamId.Get() == nil {
		var ret float32
		return ret
	}

	return *o.ParamId.Get()
}

// GetParamIdOk returns a tuple with the ParamId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParamUp) GetParamIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParamId.Get(), o.ParamId.IsSet()
}

// SetParamId sets field value
func (o *ParamUp) SetParamId(v float32) {
	o.ParamId.Set(&v)
}

// GetDeviceId returns the DeviceId field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *ParamUp) GetDeviceId() float32 {
	if o == nil || o.DeviceId.Get() == nil {
		var ret float32
		return ret
	}

	return *o.DeviceId.Get()
}

// GetDeviceIdOk returns a tuple with the DeviceId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParamUp) GetDeviceIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeviceId.Get(), o.DeviceId.IsSet()
}

// SetDeviceId sets field value
func (o *ParamUp) SetDeviceId(v float32) {
	o.DeviceId.Set(&v)
}

// GetValueStr returns the ValueStr field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ParamUp) GetValueStr() string {
	if o == nil || o.ValueStr.Get() == nil {
		var ret string
		return ret
	}

	return *o.ValueStr.Get()
}

// GetValueStrOk returns a tuple with the ValueStr field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParamUp) GetValueStrOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ValueStr.Get(), o.ValueStr.IsSet()
}

// SetValueStr sets field value
func (o *ParamUp) SetValueStr(v string) {
	o.ValueStr.Set(&v)
}

// GetUpTime returns the UpTime field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *ParamUp) GetUpTime() time.Time {
	if o == nil || o.UpTime.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.UpTime.Get()
}

// GetUpTimeOk returns a tuple with the UpTime field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParamUp) GetUpTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpTime.Get(), o.UpTime.IsSet()
}

// SetUpTime sets field value
func (o *ParamUp) SetUpTime(v time.Time) {
	o.UpTime.Set(&v)
}

// GetUpSss returns the UpSss field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *ParamUp) GetUpSss() float32 {
	if o == nil || o.UpSss.Get() == nil {
		var ret float32
		return ret
	}

	return *o.UpSss.Get()
}

// GetUpSssOk returns a tuple with the UpSss field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ParamUp) GetUpSssOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpSss.Get(), o.UpSss.IsSet()
}

// SetUpSss sets field value
func (o *ParamUp) SetUpSss(v float32) {
	o.UpSss.Set(&v)
}

func (o ParamUp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ParamUp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["up_id"] = o.UpId
	toSerialize["param_id"] = o.ParamId.Get()
	toSerialize["device_id"] = o.DeviceId.Get()
	toSerialize["value_str"] = o.ValueStr.Get()
	toSerialize["up_time"] = o.UpTime.Get()
	toSerialize["up_sss"] = o.UpSss.Get()
	return toSerialize, nil
}

func (o *ParamUp) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"up_id",
		"param_id",
		"device_id",
		"value_str",
		"up_time",
		"up_sss",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varParamUp := _ParamUp{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varParamUp)

	if err != nil {
		return err
	}

	*o = ParamUp(varParamUp)

	return err
}

type NullableParamUp struct {
	value *ParamUp
	isSet bool
}

func (v NullableParamUp) Get() *ParamUp {
	return v.value
}

func (v *NullableParamUp) Set(val *ParamUp) {
	v.value = val
	v.isSet = true
}

func (v NullableParamUp) IsSet() bool {
	return v.isSet
}

func (v *NullableParamUp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParamUp(val *ParamUp) *NullableParamUp {
	return &NullableParamUp{value: val, isSet: true}
}

func (v NullableParamUp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParamUp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


