/*
HREG API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiParamDefinesGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiParamDefinesGet200Response{}

// ApiParamDefinesGet200Response struct for ApiParamDefinesGet200Response
type ApiParamDefinesGet200Response struct {
	Params []ParamDefines `json:"params"`
}

type _ApiParamDefinesGet200Response ApiParamDefinesGet200Response

// NewApiParamDefinesGet200Response instantiates a new ApiParamDefinesGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiParamDefinesGet200Response(params []ParamDefines) *ApiParamDefinesGet200Response {
	this := ApiParamDefinesGet200Response{}
	this.Params = params
	return &this
}

// NewApiParamDefinesGet200ResponseWithDefaults instantiates a new ApiParamDefinesGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiParamDefinesGet200ResponseWithDefaults() *ApiParamDefinesGet200Response {
	this := ApiParamDefinesGet200Response{}
	return &this
}

// GetParams returns the Params field value
func (o *ApiParamDefinesGet200Response) GetParams() []ParamDefines {
	if o == nil {
		var ret []ParamDefines
		return ret
	}

	return o.Params
}

// GetParamsOk returns a tuple with the Params field value
// and a boolean to check if the value has been set.
func (o *ApiParamDefinesGet200Response) GetParamsOk() ([]ParamDefines, bool) {
	if o == nil {
		return nil, false
	}
	return o.Params, true
}

// SetParams sets field value
func (o *ApiParamDefinesGet200Response) SetParams(v []ParamDefines) {
	o.Params = v
}

func (o ApiParamDefinesGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiParamDefinesGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["params"] = o.Params
	return toSerialize, nil
}

func (o *ApiParamDefinesGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"params",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiParamDefinesGet200Response := _ApiParamDefinesGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiParamDefinesGet200Response)

	if err != nil {
		return err
	}

	*o = ApiParamDefinesGet200Response(varApiParamDefinesGet200Response)

	return err
}

type NullableApiParamDefinesGet200Response struct {
	value *ApiParamDefinesGet200Response
	isSet bool
}

func (v NullableApiParamDefinesGet200Response) Get() *ApiParamDefinesGet200Response {
	return v.value
}

func (v *NullableApiParamDefinesGet200Response) Set(val *ApiParamDefinesGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiParamDefinesGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiParamDefinesGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiParamDefinesGet200Response(val *ApiParamDefinesGet200Response) *NullableApiParamDefinesGet200Response {
	return &NullableApiParamDefinesGet200Response{value: val, isSet: true}
}

func (v NullableApiParamDefinesGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiParamDefinesGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


