/*
HREG API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiDeviceGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiDeviceGet200Response{}

// ApiDeviceGet200Response struct for ApiDeviceGet200Response
type ApiDeviceGet200Response struct {
	Devices []Device `json:"devices"`
}

type _ApiDeviceGet200Response ApiDeviceGet200Response

// NewApiDeviceGet200Response instantiates a new ApiDeviceGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiDeviceGet200Response(devices []Device) *ApiDeviceGet200Response {
	this := ApiDeviceGet200Response{}
	this.Devices = devices
	return &this
}

// NewApiDeviceGet200ResponseWithDefaults instantiates a new ApiDeviceGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiDeviceGet200ResponseWithDefaults() *ApiDeviceGet200Response {
	this := ApiDeviceGet200Response{}
	return &this
}

// GetDevices returns the Devices field value
func (o *ApiDeviceGet200Response) GetDevices() []Device {
	if o == nil {
		var ret []Device
		return ret
	}

	return o.Devices
}

// GetDevicesOk returns a tuple with the Devices field value
// and a boolean to check if the value has been set.
func (o *ApiDeviceGet200Response) GetDevicesOk() ([]Device, bool) {
	if o == nil {
		return nil, false
	}
	return o.Devices, true
}

// SetDevices sets field value
func (o *ApiDeviceGet200Response) SetDevices(v []Device) {
	o.Devices = v
}

func (o ApiDeviceGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiDeviceGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["devices"] = o.Devices
	return toSerialize, nil
}

func (o *ApiDeviceGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"devices",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiDeviceGet200Response := _ApiDeviceGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiDeviceGet200Response)

	if err != nil {
		return err
	}

	*o = ApiDeviceGet200Response(varApiDeviceGet200Response)

	return err
}

type NullableApiDeviceGet200Response struct {
	value *ApiDeviceGet200Response
	isSet bool
}

func (v NullableApiDeviceGet200Response) Get() *ApiDeviceGet200Response {
	return v.value
}

func (v *NullableApiDeviceGet200Response) Set(val *ApiDeviceGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiDeviceGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiDeviceGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiDeviceGet200Response(val *ApiDeviceGet200Response) *NullableApiDeviceGet200Response {
	return &NullableApiDeviceGet200Response{value: val, isSet: true}
}

func (v NullableApiDeviceGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiDeviceGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


