/*
HREG API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiParamPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiParamPostRequest{}

// ApiParamPostRequest struct for ApiParamPostRequest
type ApiParamPostRequest struct {
	DeviceId float32 `json:"device_id"`
	ParamId float32 `json:"param_id"`
	ValueStr string `json:"value_str"`
}

type _ApiParamPostRequest ApiParamPostRequest

// NewApiParamPostRequest instantiates a new ApiParamPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiParamPostRequest(deviceId float32, paramId float32, valueStr string) *ApiParamPostRequest {
	this := ApiParamPostRequest{}
	this.DeviceId = deviceId
	this.ParamId = paramId
	this.ValueStr = valueStr
	return &this
}

// NewApiParamPostRequestWithDefaults instantiates a new ApiParamPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiParamPostRequestWithDefaults() *ApiParamPostRequest {
	this := ApiParamPostRequest{}
	return &this
}

// GetDeviceId returns the DeviceId field value
func (o *ApiParamPostRequest) GetDeviceId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value
// and a boolean to check if the value has been set.
func (o *ApiParamPostRequest) GetDeviceIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceId, true
}

// SetDeviceId sets field value
func (o *ApiParamPostRequest) SetDeviceId(v float32) {
	o.DeviceId = v
}

// GetParamId returns the ParamId field value
func (o *ApiParamPostRequest) GetParamId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ParamId
}

// GetParamIdOk returns a tuple with the ParamId field value
// and a boolean to check if the value has been set.
func (o *ApiParamPostRequest) GetParamIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ParamId, true
}

// SetParamId sets field value
func (o *ApiParamPostRequest) SetParamId(v float32) {
	o.ParamId = v
}

// GetValueStr returns the ValueStr field value
func (o *ApiParamPostRequest) GetValueStr() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ValueStr
}

// GetValueStrOk returns a tuple with the ValueStr field value
// and a boolean to check if the value has been set.
func (o *ApiParamPostRequest) GetValueStrOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValueStr, true
}

// SetValueStr sets field value
func (o *ApiParamPostRequest) SetValueStr(v string) {
	o.ValueStr = v
}

func (o ApiParamPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiParamPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["device_id"] = o.DeviceId
	toSerialize["param_id"] = o.ParamId
	toSerialize["value_str"] = o.ValueStr
	return toSerialize, nil
}

func (o *ApiParamPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"device_id",
		"param_id",
		"value_str",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiParamPostRequest := _ApiParamPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiParamPostRequest)

	if err != nil {
		return err
	}

	*o = ApiParamPostRequest(varApiParamPostRequest)

	return err
}

type NullableApiParamPostRequest struct {
	value *ApiParamPostRequest
	isSet bool
}

func (v NullableApiParamPostRequest) Get() *ApiParamPostRequest {
	return v.value
}

func (v *NullableApiParamPostRequest) Set(val *ApiParamPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiParamPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiParamPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiParamPostRequest(val *ApiParamPostRequest) *NullableApiParamPostRequest {
	return &NullableApiParamPostRequest{value: val, isSet: true}
}

func (v NullableApiParamPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiParamPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


