/*
HREG API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Device type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Device{}

// Device struct for Device
type Device struct {
	DeviceId float32 `json:"device_id"`
	DeviceName string `json:"device_name"`
	Seriennum NullableString `json:"Seriennum"`
	LastDeviceIp NullableString `json:"last_device_ip"`
	LastTimeOnline NullableTime `json:"last_time_online"`
	Hwver NullableString `json:"hwver"`
	Swver NullableString `json:"swver"`
	CustUserId NullableFloat32 `json:"cust_user_id"`
	DevtypId NullableFloat32 `json:"devtyp_id"`
	MbNums NullableString `json:"mb_nums"`
	Action NullableFloat32 `json:"action"`
	MbSerno NullableString `json:"mb_serno"`
}

type _Device Device

// NewDevice instantiates a new Device object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDevice(deviceId float32, deviceName string, seriennum NullableString, lastDeviceIp NullableString, lastTimeOnline NullableTime, hwver NullableString, swver NullableString, custUserId NullableFloat32, devtypId NullableFloat32, mbNums NullableString, action NullableFloat32, mbSerno NullableString) *Device {
	this := Device{}
	this.DeviceId = deviceId
	this.DeviceName = deviceName
	this.Seriennum = seriennum
	this.LastDeviceIp = lastDeviceIp
	this.LastTimeOnline = lastTimeOnline
	this.Hwver = hwver
	this.Swver = swver
	this.CustUserId = custUserId
	this.DevtypId = devtypId
	this.MbNums = mbNums
	this.Action = action
	this.MbSerno = mbSerno
	return &this
}

// NewDeviceWithDefaults instantiates a new Device object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceWithDefaults() *Device {
	this := Device{}
	return &this
}

// GetDeviceId returns the DeviceId field value
func (o *Device) GetDeviceId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value
// and a boolean to check if the value has been set.
func (o *Device) GetDeviceIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceId, true
}

// SetDeviceId sets field value
func (o *Device) SetDeviceId(v float32) {
	o.DeviceId = v
}

// GetDeviceName returns the DeviceName field value
func (o *Device) GetDeviceName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceName
}

// GetDeviceNameOk returns a tuple with the DeviceName field value
// and a boolean to check if the value has been set.
func (o *Device) GetDeviceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceName, true
}

// SetDeviceName sets field value
func (o *Device) SetDeviceName(v string) {
	o.DeviceName = v
}

// GetSeriennum returns the Seriennum field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Device) GetSeriennum() string {
	if o == nil || o.Seriennum.Get() == nil {
		var ret string
		return ret
	}

	return *o.Seriennum.Get()
}

// GetSeriennumOk returns a tuple with the Seriennum field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Device) GetSeriennumOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Seriennum.Get(), o.Seriennum.IsSet()
}

// SetSeriennum sets field value
func (o *Device) SetSeriennum(v string) {
	o.Seriennum.Set(&v)
}

// GetLastDeviceIp returns the LastDeviceIp field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Device) GetLastDeviceIp() string {
	if o == nil || o.LastDeviceIp.Get() == nil {
		var ret string
		return ret
	}

	return *o.LastDeviceIp.Get()
}

// GetLastDeviceIpOk returns a tuple with the LastDeviceIp field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Device) GetLastDeviceIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastDeviceIp.Get(), o.LastDeviceIp.IsSet()
}

// SetLastDeviceIp sets field value
func (o *Device) SetLastDeviceIp(v string) {
	o.LastDeviceIp.Set(&v)
}

// GetLastTimeOnline returns the LastTimeOnline field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *Device) GetLastTimeOnline() time.Time {
	if o == nil || o.LastTimeOnline.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.LastTimeOnline.Get()
}

// GetLastTimeOnlineOk returns a tuple with the LastTimeOnline field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Device) GetLastTimeOnlineOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastTimeOnline.Get(), o.LastTimeOnline.IsSet()
}

// SetLastTimeOnline sets field value
func (o *Device) SetLastTimeOnline(v time.Time) {
	o.LastTimeOnline.Set(&v)
}

// GetHwver returns the Hwver field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Device) GetHwver() string {
	if o == nil || o.Hwver.Get() == nil {
		var ret string
		return ret
	}

	return *o.Hwver.Get()
}

// GetHwverOk returns a tuple with the Hwver field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Device) GetHwverOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Hwver.Get(), o.Hwver.IsSet()
}

// SetHwver sets field value
func (o *Device) SetHwver(v string) {
	o.Hwver.Set(&v)
}

// GetSwver returns the Swver field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Device) GetSwver() string {
	if o == nil || o.Swver.Get() == nil {
		var ret string
		return ret
	}

	return *o.Swver.Get()
}

// GetSwverOk returns a tuple with the Swver field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Device) GetSwverOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Swver.Get(), o.Swver.IsSet()
}

// SetSwver sets field value
func (o *Device) SetSwver(v string) {
	o.Swver.Set(&v)
}

// GetCustUserId returns the CustUserId field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *Device) GetCustUserId() float32 {
	if o == nil || o.CustUserId.Get() == nil {
		var ret float32
		return ret
	}

	return *o.CustUserId.Get()
}

// GetCustUserIdOk returns a tuple with the CustUserId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Device) GetCustUserIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustUserId.Get(), o.CustUserId.IsSet()
}

// SetCustUserId sets field value
func (o *Device) SetCustUserId(v float32) {
	o.CustUserId.Set(&v)
}

// GetDevtypId returns the DevtypId field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *Device) GetDevtypId() float32 {
	if o == nil || o.DevtypId.Get() == nil {
		var ret float32
		return ret
	}

	return *o.DevtypId.Get()
}

// GetDevtypIdOk returns a tuple with the DevtypId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Device) GetDevtypIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DevtypId.Get(), o.DevtypId.IsSet()
}

// SetDevtypId sets field value
func (o *Device) SetDevtypId(v float32) {
	o.DevtypId.Set(&v)
}

// GetMbNums returns the MbNums field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Device) GetMbNums() string {
	if o == nil || o.MbNums.Get() == nil {
		var ret string
		return ret
	}

	return *o.MbNums.Get()
}

// GetMbNumsOk returns a tuple with the MbNums field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Device) GetMbNumsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MbNums.Get(), o.MbNums.IsSet()
}

// SetMbNums sets field value
func (o *Device) SetMbNums(v string) {
	o.MbNums.Set(&v)
}

// GetAction returns the Action field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *Device) GetAction() float32 {
	if o == nil || o.Action.Get() == nil {
		var ret float32
		return ret
	}

	return *o.Action.Get()
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Device) GetActionOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Action.Get(), o.Action.IsSet()
}

// SetAction sets field value
func (o *Device) SetAction(v float32) {
	o.Action.Set(&v)
}

// GetMbSerno returns the MbSerno field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Device) GetMbSerno() string {
	if o == nil || o.MbSerno.Get() == nil {
		var ret string
		return ret
	}

	return *o.MbSerno.Get()
}

// GetMbSernoOk returns a tuple with the MbSerno field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Device) GetMbSernoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MbSerno.Get(), o.MbSerno.IsSet()
}

// SetMbSerno sets field value
func (o *Device) SetMbSerno(v string) {
	o.MbSerno.Set(&v)
}

func (o Device) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Device) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["device_id"] = o.DeviceId
	toSerialize["device_name"] = o.DeviceName
	toSerialize["Seriennum"] = o.Seriennum.Get()
	toSerialize["last_device_ip"] = o.LastDeviceIp.Get()
	toSerialize["last_time_online"] = o.LastTimeOnline.Get()
	toSerialize["hwver"] = o.Hwver.Get()
	toSerialize["swver"] = o.Swver.Get()
	toSerialize["cust_user_id"] = o.CustUserId.Get()
	toSerialize["devtyp_id"] = o.DevtypId.Get()
	toSerialize["mb_nums"] = o.MbNums.Get()
	toSerialize["action"] = o.Action.Get()
	toSerialize["mb_serno"] = o.MbSerno.Get()
	return toSerialize, nil
}

func (o *Device) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"device_id",
		"device_name",
		"Seriennum",
		"last_device_ip",
		"last_time_online",
		"hwver",
		"swver",
		"cust_user_id",
		"devtyp_id",
		"mb_nums",
		"action",
		"mb_serno",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDevice := _Device{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDevice)

	if err != nil {
		return err
	}

	*o = Device(varDevice)

	return err
}

type NullableDevice struct {
	value *Device
	isSet bool
}

func (v NullableDevice) Get() *Device {
	return v.value
}

func (v *NullableDevice) Set(val *Device) {
	v.value = val
	v.isSet = true
}

func (v NullableDevice) IsSet() bool {
	return v.isSet
}

func (v *NullableDevice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDevice(val *Device) *NullableDevice {
	return &NullableDevice{value: val, isSet: true}
}

func (v NullableDevice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDevice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


